steamKey: <key>
mods: # Recommended mods
  - screepsmod-auth
  - screepsmod-admin-utils
  - screepsmod-mongo # You must install and start `mongodb` and `redis` before this mod will work
  - screepsmod-history
bots:
  kasami: screeps-bot-kasamibot
  quorum: "./bots/quorum/dist"
  tooangel: "./bots/tooangel/dist"
  hivemind: "./bots/hivemind/dist"
  overmind: "./bots/overmind/dist"
  zeswarm: "./bots/zeswarm/dist"
serverConfig: # This section requires screepsmod-admin-utils to work
  welcomeText: |
    <h1 style="text-align: center;">NDScreeps Server</h1>
  constants: # Used to override screeps constants
    TEST_CONSTANT: 123
  tickRate: 1500 # In milliseconds. This is a lower bound. Users reported problems when set too low.
