{
 "title": "Screeps Dashboard",
 "tags": [ "screeps" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "room", "query": "screeps.dean.rooms.*" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms", "label": "Usage" }
   ],
   "targets": [
    {
     "target": "alias(screeps.dean.cpu.used, 'Used')"
    },
    {
     "target": "alias(screeps.dean.cpu.bucket, 'Bucket')"
    },
    {
     "target": "alias(screeps.dean.cpu.limit, 'Limit')"
    }
   ]
  },
  {
   "title": "Current Bucket",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "screeps.dean.cpu.bucket" }
   ]
  },
  {
   "title": "Ticks Per Stats Update",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(derivative(screeps.dean.time), 'Ticks Per Update')"
    }
   ]
  },
  { "title": "Shard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "GCL",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "screeps.dean.gcl.level" }
   ]
  },
  {
   "title": "GCL Progress",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 9 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "target": "divideSeries(screeps.dean.gcl.progress, #B)"
    }
   ]
  },
  {
   "title": "Time to Next GCL",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "divideSeries(diffSeries(screeps.dean.gcl.progressTotal, #B), #C)",
     "targetFull": "divideSeries(diffSeries(screeps.dean.gcl.progressTotal, screeps.dean.gcl.progress), scaleToSeconds(movingAverage(screeps.dean.gcl.progress, '1hour'), 1))"
    }
   ]
  },
  {
   "title": "GCL Upgrade",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "alias(divideSeries(screeps.dean.gcl.progress, #B), 'GCL per tick')",
     "targetFull": "alias(divideSeries(screeps.dean.gcl.progress, derivative(screeps.dean.time)), 'GCL per tick')"
    },
    {
     "target": "alias(movingAverage(divideSeries(screeps.dean.gcl.progress, #B), '1hour'), '1hr Moving Average')",
     "targetFull": "alias(movingAverage(divideSeries(screeps.dean.gcl.progress, derivative(screeps.dean.time)), '1hour'), '1hr Moving Average')"
    }
   ]
  },
  {
   "title": "Global Stored Energy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(screeps.dean.rooms.*.energyAvailable), 'Spawns and Extensions')"
    },
    {
     "target": "alias(sumSeries(screeps.dean.rooms.*.energyCapacityAvailable), 'Energy Capacity')"
    }
   ]
  },
  { "title": "$room", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }, "repeat": "room" },
  {
   "title": "RCL",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "screeps.dean.rooms.$room.controllerLevel"
    }
   ]
  },
  {
   "title": "RCL progress",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 18 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "target": "divideSeries(screeps.dean.rooms.$room.controllerProgress, #B)"
    }
   ]
  },
  {
   "title": "Time to Next RCL",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "divideSeries(diffSeries(screeps.dean.rooms.$room.controllerProgressTotal, #B), #C)",
     "targetFull": "divideSeries(diffSeries(screeps.dean.rooms.$room.controllerProgressTotal, screeps.dean.rooms.$room.controllerProgress), scaleToSeconds(movingAverage(screeps.dean.rooms.$room.controllerProgress, '1hour'), 1))"
    }
   ]
  },
  {
   "title": "RCL Upgrade",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "alias(divideSeries(screeps.dean.rooms.$room.controllerProgress, #C), 'RCL per tick')",
     "targetFull": "alias(divideSeries(screeps.dean.rooms.$room.controllerProgress, derivative(screeps.dean.time)), 'RCL per tick')"
    },
    {
     "target": "alias(movingAverage(divideSeries(screeps.dean.rooms.$room.controllerProgress, #C), '1hour'), '1hr Moving Average')",
     "targetFull": "alias(movingAverage(divideSeries(screeps.dean.rooms.$room.controllerProgress, derivative(screeps.dean.time)), '1hour'), '1hr Moving Average')"
    }
   ]
  },
  {
   "title": "Room Stored Energy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(screeps.dean.rooms.$room.energyAvailable, 'Spawns and Extensions')"
    },
    {
     "target": "alias(screeps.dean.rooms.$room.energyCapacityAvailable, 'Energy Capacity')"
    }
   ]
  }
 ]
}